---
- hosts: localhost
  gather_facts: no
  connection: localhost
  vars_files:
    - ./vars.yaml  
   
  tasks:
  - name: Include task list in play vpc
    ansible.builtin.import_tasks:
      file: "./tasks/1_vpc.yaml"
    
  - name: Include task list in play subnet
    ansible.builtin.import_tasks:
      file: "./tasks/2_subnet.yaml"    

  - name: Include task list in play security_group
    ansible.builtin.import_tasks:
      file: "./tasks/3_security_group.yaml" 

  - name: Include task list in play efs
    ansible.builtin.import_tasks:
      file: "./tasks/9_efs.yaml"

- hosts: web_asg   
  vars: 
    ansible_ssh_common_args:
      -o ProxyCommand="ssh
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -i ~/.ssh/ec2-key.pem
      -W %h:%p ec2-user@{{ hostvars[groups['project_ec2_bastion'][0]]["public_ip_address"] }}"  
  tasks:    
  - name: Mount up device web efs 
    ansible.posix.mount:
      path: /home/ec2-user/efs
      src: "fs-0178375f0a38f40d0:/"
      fstype: nfs4
      state: mounted
    
# ############ mount efs file system in was ec2 ###########                  
- hosts: was_asg   
  vars: 
    ansible_ssh_common_args:
      -o ProxyCommand="ssh
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -i ~/.ssh/ec2-key.pem
      -W %h:%p ec2-user@{{ hostvars[groups['project_ec2_bastion'][0]]["public_ip_address"] }}"
  tasks:    
  - name: Mount up device was efs
    ansible.posix.mount:
      path: /home/ec2-user/efs
      src: "fs-0d915e67d4436c3da:/"
      fstype: nfs4
      state: mounted   