---
- hosts: localhost  
  gather_facts: no
  connection: localhost
  vars:
    - ./vars.yaml   

  tasks:
  - name: Include task list in play 1~9
    ansible.builtin.import_tasks:
      file: {{ item }}
    loop:
      - ./tasks/1_vpc.yaml      
      - ./tasks/2_subnet.yaml      
      - ./tasks/3_security_group.yaml   
      - ./tasks/4_routing_tables.yaml   
      - ./tasks/5_ec2.yaml   
      - ./tasks/6_auto_scaling_group.yaml   
      - ./tasks/7_load_balancer.yaml   
      - ./tasks/8_cloudwatch.yaml   
      - ./tasks/9_efs.yaml   


- hosts: project_ec2_bastion
  tasks:
  - name: Include task list in play 10
    ansible.builtin.import_tasks:
      file: ./tasks/10_bastion.yaml 

- hosts: 
  - web_asg
  - was_asg
  gather_facts: no
  vars: 
    ansible_ssh_common_args:
      -o ProxyCommand="ssh
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -i ~/.ssh/ec2-key.pem
      -W %h:%p ec2-user@{{ hostvars[groups['project_ec2_bastion'][0]]["public_ip_address"] }}"
  tasks:
  - name: Include task list in play 11
    ansible.builtin.import_tasks:
      file: ./tasks/11_private.yaml       

- hosts: web_asg
  gather_facts: no
  vars: 
    ansible_ssh_common_args:
      -o ProxyCommand="ssh
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -i ~/.ssh/ec2-key.pem
      -W %h:%p ec2-user@{{ hostvars[groups['project_ec2_bastion'][0]]["public_ip_address"] }}"  
  tasks:
  - name: Include task list in play 12
    ansible.builtin.import_tasks:
      file: ./tasks/12_webservice.yaml     

- hosts: was_asg
  gather_facts: no
  vars: 
    ansible_ssh_common_args:
      -o ProxyCommand="ssh
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -i ~/.ssh/ec2-key.pem
      -W %h:%p ec2-user@{{ hostvars[groups['project_ec2_bastion'][0]]["public_ip_address"] }}"  
  tasks:
  - name: Include task list in play 13
    ansible.builtin.import_tasks:
      file: ./tasks/13_wasbservice.yaml