---
- hosts: localhost  
  vars_files:
    - ./vars.yaml  
  tasks:
  - name: Include task list in play
    ansible.builtin.include_tasks:
      file: ./tasks/1_vpc.yaml   

  - name: Include task list in play
    ansible.builtin.include_tasks:
      file: ./tasks/2_subnet.yaml    

  - name: Include task list in play
    ansible.builtin.include_tasks:
      file: ./tasks/3_security_group.yaml    

  # - name: change a subnet group to RDS
  #   amazon.aws.rds_subnet_group:
  #     state: "{{ state }}"
  #     name: rds_subnets
  #     description: RDS subnet
  #     subnets:
  #       - "{{ subnet_db1_result.subnet.id }}"
  #       - "{{ subnet_db2_result.subnet.id }}"

  - name: Create RDS instance
    amazon.aws.rds_instance:
      command: "create"
      db_instance_identifier: "{{ rds_ec2_name_01 }}"
      engine: "mysql"
      engine_version: "8.0.35"
      instance_class: "db.t2.micro"
      allocated_storage: 20
      db_name: "{{ rds_name_01 }}"
      master_username: "my_username"
      master_user_password: "my_password"
      db_security_groups:   
        - "{{ security_group_db_result.group_id }}" 
      db_subnet_group_name: "{{ subnet_db1_result.subnet.name }}"       
      tags:
        - name: "{{ rds_name_01 }}"