 #######################################
  ############  vim rds.yml  ############
  #######################################

# create RDS Subnets for rds service
- name: change a subnet group to RDS
  amazon.aws.rds_subnet_group:
    state: "{{ state }}"
    name: rds_subnets
    description: RDS subnet
    subnets:
      - "{{ subnet_db1_result.subnet.id }}"
      - "{{ subnet_db2_result.subnet.id }}"

- name: Create RDS instance
  amazon.aws.rds_instance:
    db_instance_identifier: "{{ rds_ec2_name_01 }}"
    engine: "mysql"
    engine_version: "8.0.35"
    db_instance_class: "db.m5.large"
    allocated_storage: 20
    db_name: "{{ rds_name_01 }}"
    master_username: my_username
    master_user_password: my_password
    vpc_security_group_ids: "{{ security_group_db_result.group_id }}" 
    db_subnet_group_name: "rds_subnets"       
    multi_az: true
    tags:
      name:  "{{ rds_name_01 }}"
  register: rds_result      
      
