#########################################################################
################  private ec2(web, was) ansible ###########################
#########################################################################


- hosts: 
- web_asg
- was_asg
gather_facts: yes
vars: 
  ansible_ssh_common_args:
    -o ProxyCommand="ssh
    -o StrictHostKeyChecking=no
    -o UserKnownHostsFile=/dev/null
    -i ~/.ssh/ec2-key.pem
    -W %h:%p ec2-user@{{ hostvars[groups['project_ec2_bastion'][0]]["public_ip_address"] }}"   
tasks:

############ ec2-user join group whell ###########
  - name: Add the user 'ec2-user' with a bash shell, appending the group 'wheel' 
    ansible.builtin.user:
      name: ec2-user
      shell: /bin/bash
      groups: wheel       
      append: yes        

############ copy sudoers file ###########
  - name: Copy a "sudoers" file into place for ansible
    ansible.builtin.copy:
      src: ./sudoers
      dest: /etc/sudoers
      owner: root
      group: root    

############ create a .ssh directory  ###########
  - name: Create a directory ".ssh"
    ansible.builtin.file:
      path: /home/ec2-user/.ssh
      state: directory
      mode: '0755'


############ dnf install python, nfs, efs utils ###########  
  - name: Install the latest version of ansible, pyhon3-pip
    ansible.builtin.dnf:
      name:          
        - python3-pip
        - amazon-efs-utils
        - nfs-utils
      state: latest           

#########################################################################
################  private ec2(web) ansible ###########################
#########################################################################

tasks: 
############ mount efs file system in web ec2 ###########                  
- name: Mount up device by UUID
  hosts: web_asg  
  ansible.posix.mount:
    path: /home/ec2-user/efs
    src: "{{ web_efs_result.file_system_id }}"
    fstype: nfs4
    state: mounted

#########################################################################
################  private ec2(was) ansible ###########################
#########################################################################      

############ mount efs file system in was ec2 ###########                  
- name: Mount up device by UUID
  hosts: was_asg    
  ansible.posix.mount:
    path: /home/ec2-user/efs
    src: "{{ was_efs_result.file_system_id }}"
    fstype: nfs4
    state: mounted
