#########################################################################
################  private ec2(web) ansible ###########################
#########################################################################


############ copy blind_web files  ###########
- name: Copy a "blind_web" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/blind_web/
    dest: /home/ec2-user/service/blind_web/
    mode: 755

############ copy blind_web.service ###########
- name: Copy a "bilind_web.service" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/web.service
    dest: /etc/systemd/system/blind_web.service
    owner: root
    group: root
    mode: 755      

############ systemctl enable --now blind_web ###########
- name: Enable service blind_web.service and ensure 
  ansible.builtin.systemd_service:
    name: blind_web
    enabled: true
    daemon_reload: true
    state: started
   
############ mount efs file system in web ec2 ###########                  
- name: Mount up device web efs 
  ansible.posix.mount:
    path: /home/ec2-user/efs
    src: "fs-0178375f0a38f40d0.efs.ap-northeast-1.amazonaws.com:/"
    fstype: nfs4
    state: mounted
