#########################################################################
################  private ec2(web) ansible ###########################
#########################################################################


############ copy blind_web files  ###########
- name: Copy a "blind_web" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/blind_web/
    dest: /home/ec2-user/service/blind_web/
    mode: 755

############ copy blind_web.service ###########
- name: Copy a "bilind_web.service" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/web.service
    dest: /etc/systemd/system/blind_web.service
    owner: root
    group: root
    mode: 755      

############ systemctl enable --now blind_web ###########
- name: Enable service blind_web.service and ensure 
  ansible.builtin.systemd_service:
    name: blind_web
    enabled: true
    daemon_reload: true
    state: started
   
############ mount efs file system in web ec2 ###########                  
- name: Mount up device web efs 
  ansible.posix.mount:
    path: /home/ec2-user/efs
    src: "fs-0178375f0a38f40d0.efs.ap-northeast-1.amazonaws.com:/"
    fstype: nfs4
    state: mounted

# src 부분에서 efs 생성의 return값을 반환하지 못하여 직접 입력

- name: Replace a webservice in loadbalancer
  ansible.builtin.lineinfile:
    path: /home/ec2-user/service/board.py
    regexp: '{{ inlb_result.dns_name }}:5000'
    line: 'http://internal-internalELB-newnew-943065277.ap-northeast-1.elb.amazonaws.com:5000'

- name: Replace a webservice in loadbalancer
  ansible.builtin.lineinfile:
    path: /home/ec2-user/service/{{ item }}
    regexp: '{{ rds1_result.endpoint.address }}'
    line: 'blind.cq83gr1p9r0f.ap-northeast-1.rds.amazonaws.com'
  loop:
    - blind_board_DAO.py  
    - blind_member_DAO.py
    - blind_reply_DAO.py