#########################################################################
################  private ec2(was) ansible ###########################
#########################################################################      


 ############ copy blind_was files  ###########
- name: Copy a "blind_was" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/blind_was/
    dest: /home/ec2-user/service/blind_was/
    mode: 755

############ copy blind_was.service ###########
- name: Copy a "bilind_was.service" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/was.service
    dest: /etc/systemd/system/blind_was.service
    owner: root
    group: root
    mode: 755      

############ systemctl enable --now blind_was ###########
- name: Enable service blind_was.service and ensure 
  ansible.builtin.systemd_service:
    name: blind_was
    enabled: true
    daemon_reload: true
    state: started

# ############ mount efs file system in was ec2 ###########                  
- name: Mount up device was efs
  ansible.posix.mount:
    path: /home/ec2-user/efs
    src: "{{ was_efs_result.file_system_id }}:/"
    fstype: nfs4
    state: mounted         

    