#########################################################################
################  private ec2(was) ansible ###########################
#########################################################################      


 ############ copy blind_was files  ###########
- name: Copy a "blind_was" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/blind_was/
    dest: /home/ec2-user/service/blind_was/
    mode: 755

############ copy blind_was.service ###########
- name: Copy a "bilind_was.service" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/was.service
    dest: /etc/systemd/system/blind_was.service
    owner: root
    group: root
    mode: 755      

############ systemctl enable --now blind_was ###########
- name: Enable service blind_was.service and ensure 
  ansible.builtin.systemd_service:
    name: blind_was
    enabled: true
    daemon_reload: true
    state: started

# ############ mount efs file system in was ec2 ###########                  
- name: Mount up device was efs
  ansible.posix.mount:
    path: /home/ec2-user/efs
    src: "fs-0d915e67d4436c3da.efs.ap-northeast-1.amazonaws.com:/"
    fstype: nfs4
    state: mounted  

# src 부분에서 efs 생성의 return값을 반환하지 못하여 직접 입력      

- name: Replace a webservice in loadbalancer
  ansible.builtin.lineinfile:
    path: /home/ec2-user/service/board.py
    regexp: '{{ inlb_result.dns_name }}:5000'
    line: 'http://internal-internalELB-newnew-943065277.ap-northeast-1.elb.amazonaws.com:5000'

- name: Replace a webservice service in rds mount point
  ansible.builtin.lineinfile:
    path: /home/ec2-user/service/{{ item }}
    regexp: '{{ rds_result.endpoint.address }}'
    line: 'blind.cq83gr1p9r0f.ap-northeast-1.rds.amazonaws.com'
  loop:
    - blind_board_DAO.py  
    - blind_member_DAO.py
    - blind_reply_DAO.py

# lineinfile 사용하여 로드벨런서,rds 입력  
