#########################################################################
################  private ec2(was) ansible ###########################
#########################################################################      

############ create blind_was directory   ###########
- name: Create a directory "blind_was"
  ansible.builtin.file:
    path: /home/ec2-user/service/blind_was
    state: directory
    mode: '0755'

 ############ copy blind_was files  ###########
- name: Copy a "blind_was" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/blind_was/
    dest: /home/ec2-user/service/blind_was/
    mode: 755

############ copy blind_was.service ###########
- name: Copy a "bilind_was.service" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/was.service
    dest: /etc/systemd/system/blind_was.service
    owner: root
    group: root
    mode: 755      

############ systemctl enable --now blind_was ###########
- name: Enable service blind_was.service and ensure 
  ansible.builtin.systemd_service:
    name: blind_was
    enabled: true
    daemon_reload: true
    state: started

# ############ mount efs file system in was ec2 ###########                  
- name: Mount up device was efs
  ansible.posix.mount:
    path: /home/ec2-user/efs
    src: "fs-0d915e67d4436c3da.efs.ap-northeast-1.amazonaws.com:/"
    fstype: nfs4
    state: mounted  

# src 부분에서 efs 생성의 return값을 반환하지 못하여 직접 입력      

############# replace rds end point in service .py file ############### 
- name: Replace a wasservice service in rds mount point
  ansible.builtin.replace:
    path: /home/ec2-user/service/blind_was/{{ item }}    
    regexp: 'blind.cq83gr1p9r0f.ap-northeast-1.rds.amazonaws.com'
    replace: 'projectrdsec2.cqvnunqao1xr.ap-northeast-1.rds.amazonaws.com' 
  loop:
    - blind_board_DAO.py  
    - blind_member_DAO.py
    - blind_reply_DAO.py
# 변수 적용이 안되서 rds endpoint를 직접 입력 
