#########################################################################
################  private ec2(was) ansible ###########################
#########################################################################      


- hosts: was_asg
  gather_facts: yes
  vars: 
    ansible_ssh_common_args:
      -o ProxyCommand="ssh
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -i ~/.ssh/ec2-key.pem
      -W %h:%p ec2-user@{{ hostvars[groups['project_ec2_bastion'][0]]["public_ip_address"] }}"   
  tasks:
 
 ############ copy blind_was files  ###########
  - name: Copy a "blind_was" file into place for ansible
    ansible.builtin.copy:
      src: /home/nana/pro/files/blind_was/
      dest: /home/ec2-user/service/blind_was/
      mode: 755

############ copy blind_was.service ###########
  - name: Copy a "bilind_was.service" file into place for ansible
    ansible.builtin.copy:
      src: /home/nana/pro/files/was.service
      dest: /etc/systemd/system/blind_was.service
      owner: root
      group: root
      mode: 755      

############ systemctl enable --now blind_was ###########
  - name: Enable service blind_was.service and ensure 
    ansible.builtin.systemd_service:
      name: blind_was
      enabled: true
      daemon_reload: true
      state: started