#########################################################################
################  private ec2(web) ansible ###########################
#########################################################################

############ create blind_web directory   ###########
- name: Create a directory "blind_web"
  ansible.builtin.file:
    path: /home/ec2-user/service/blind_web
    state: directory
    mode: '0755'

############ copy blind_web files  ###########
- name: Copy a "blind_web" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/blind_web/
    dest: /home/ec2-user/service/blind_web/
    mode: 755

############ copy blind_web.service ###########
- name: Copy a "bilind_web.service" file into place for ansible
  ansible.builtin.copy:
    src: /home/nana/project/files/web.service
    dest: /etc/systemd/system/blind_web.service
    owner: root
    group: root
    mode: 755      

############ systemctl enable --now blind_web ###########
- name: Enable service blind_web.service and ensure 
  ansible.builtin.systemd_service:
    name: blind_web
    enabled: true
    daemon_reload: true
    state: started
   
############ mount efs file system in web ec2 ###########                  
- name: Mount up device web efs 
  ansible.posix.mount:
    path: /home/ec2-user/efs
    src: "fs-0178375f0a38f40d0.efs.ap-northeast-1.amazonaws.com:/"
    fstype: nfs4
    state: mounted
# src 부분에서 efs 생성의 return값을 반환하지 못하여 efs의 dns를 직접 입력

############# replace internal load balancer in board.py ###############  
- name: Replace a webservice in loadbalancer
  ansible.builtin.replace:
    path: /home/ec2-user/service/blind_web/board.py
    regexp: 'http://internal-internalELB-newnew-943065277.ap-northeast-1.elb.amazonaws.com'
    replace: 'http://internal-project-lb-internal-1432703978.ap-northeast-1.elb.amazonaws.com'
# 변수 적용이 안되서 in lb의 dns주소를 직접 입력

############# replace rds end point in service .py file ###############  
- name: Replace a webservice service in rds mount point
  ansible.builtin.replace:
    path: /home/ec2-user/service/blind_web/{{ item }}    
    regexp: 'blind.cq83gr1p9r0f.ap-northeast-1.rds.amazonaws.com'
    replace: 'projectrdsec2.cqvnunqao1xr.ap-northeast-1.rds.amazonaws.com' 
  loop:
    - blind_board_DAO.py  
    - blind_member_DAO.py
    - blind_reply_DAO.py
# 변수 적용이 안되서 rds endpoint를 직접 입력
