- name: create efs for web
  community.aws.efs:
    state: "present"
    name: "efs_name_web"
    targets:
      - subnet_id: "subnet-0d93739b4da99a8d5"
        security_groups: [" sg-02396524debb6de38" ]
      - subnet_id: "subnet-02be0fb335a7482fb"
        security_groups: [ "sg-02396524debb6de38" ]         
  register: web_efs_result

############ create efs for was ###########
- name: create efs for was
  community.aws.efs:
    state: present
    name: efs_name_was 
    targets:
      - subnet_id: "subnet-0173fef119bf747cb"
        security_groups: [ "sg-0f40fdb042c96e5dc" ]
      - subnet_id: "subnet-02f6f9e0d6880a49c"
        security_groups: [ "sg-0f40fdb042c96e5dc" ]           
  register: was_efs_result

