#################################################
################  vim efs.yml  ###################
#################################################     

############ create efs for web ###########
- name: create efs for web
  community.aws.efs:
    state: "{{ state }}"
    name: "{{ efs_name_web }}"
    targets:
      - subnet_id: "{{ subnet_web1_result.subnet.id }}"
        security_groups: ["{{ security_group_efs_web_result.group_id }}"]
      - subnet_id: "{{ subnet_web2_result.subnet.id }}"
        security_groups: ["{{ security_group_efs_web_result.group_id }}"]         
  resigter: web_efs_result

############ create efs for was ###########
- name: create efs for was
  community.aws.efs:
    state: "{{ state }}"
    name: "{{ efs_name_was }}"
    targets:
      - subnet_id: "{{ subnet_was1_result.subnet.id }}"
        security_groups: ["{{ security_group_efs_was_result.group_id }}"]
      - subnet_id: "{{ subnet_was2_result.subnet.id }}"
        security_groups: ["{{ security_group_efs_was_result.group_id }}"]           
  resigter: was_efs_result

