---
- name: install node_exporter on private
  hosts: 
    - web_asg
    - was_asg
  vars:
    ansible_ssh_common_args: 
      -o ProxyCommand="ssh 
      -o StrictHostKeyChecking=no 
      -o UserKnownHostsFile=/dev/null
      -i ~/.ssh/terraform-key
      -W %h:%p ec2-user@{{ hostvars[groups['project_ec2_bastion'][0]]["public_ip_address"] }}"
  become: True  
  gather_facts: yes
  roles:
    - role: role/node_exporter
    
- name: install prometheus & grafana on bastion
  hosts: project_ec2_bastion
  become: True  
  gather_facts: yes
  roles: 
    - role/prometheus
    - role/grafana
 
# ansible-galaxy role init node_exporter
# ansible-galaxy role init prometheus
# ansible-galaxy role init grafana