---
- hosts: localhost
  gather_facts: no
  connection: localhost
  vars_files:
    - ./vars.yaml
  tasks:
  - name: 1. creat vpc, igw, nat, eip
    ansible.builtin.import_tasks:
      file: ../tasks/1_vpc.yaml

  - name: 2. creat subnet
    ansible.builtin.import_tasks:
      file: ../tasks/2_subnet.yaml

  - name: 3. creat security_group
    ansible.builtin.import_tasks:
      file: ../tasks/3_security_group.yaml 

  - name: 4. creat eks cluster, nodegroup, master ec2
    ansible.builtin.import_tasks:
      file: ./eks_ec2.yaml 

  # - name: 5. creat eks node grouping
  #   ansible.builtin.import_tasks:
  #     file: ./ec2_control.yaml 

- hosts: project-master-ec2
  gather_facts: no
  tasks:
  - name: Running K8s Master task
    ansible.builtin.import_tasks:
      file: ./master.yaml

- hosts: project-slave-web-ec2
  gather_facts: no
  tasks:  
  - name: Running K8s web_slave Role
    ansible.builtin.import_tasks:
      file: ./slave.yaml

- hosts: project-slave-was-ec2
  gather_facts: no
  tasks:  
  - name: Running K8s was_slave Role
    ansible.builtin.import_tasks:
      file: ./slave.yaml        