---
# tasks file for kube_slave
- name: Add kubeadm repositories on Slave Node
  ansible.builtin.yum_repository:
    name: kube
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing Docker & kubeadm on Slave Node
  ansible.builtin.dnf:
    name:
      - docker
      - kubeadm
      - iproute-tc
    state: present

- name: Staring & enabling Docker & kubelet on Slave Node
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: 
    - docker
    - kubelet

- name: Updating Docker cgroup on Slave Node
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Restart Docker on Slave Node
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Updating IP tables on Slave Node
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Reloading sysctl on Slave Node
  ansible.builtin.command: sysctl --system

- name: Joining the master node
  ansible.builtin.command: "{{ hostvars[groups['ec2_master'][0]]['token']['stdout'] }}"

- name: Cleaning Caches on RAM
  ansible.builtin.shell: echo 3 > /proc/sys/vm/drop_caches