 - hosts: prometheus
   become: true
   tasks:
     - name: Install necessary packages
       yum:
         name:
           - wget
           - git
           - unzip
           - java-1.8.0-openjdk
         state: present

     - name: Download and install node_exporter
       get_url:
         url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
         dest: /tmp/node_exporter.tar.gz
       become_user: ec2-user

     - name: Extract node_exporter
       unarchive:
         src: /tmp/node_exporter.tar.gz
         dest: /usr/local/bin/
         remote_src: true
         copy: no
       become_user: root

     - name: Configure node_exporter
       template:
         src: templates/node_exporter.service.j2
         dest: /etc/systemd/system/node_exporter.service
         owner: root
         group: root
         mode: '0644'
       notify:
         - reload systemd